---
title: "Extracting elevation data using the 'elevatr' package"
author: "Aditya Ranganath"
date: "4/26/2024"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: yes
    number_sections: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=F, warning=F}
# load libraries
library(tmap)
library(elevatr)
library(raster)
library(sf)
library(tidycensus)
library(tidyverse)
```

# Generating elevation rasters using "elevatr"

```{r, message=F, warning=F, results=FALSE}
# extract Colorado polygon using tidycensus
CO_polygon<-get_decennial(geography = "state", 
                          variables = "P001001",
                          year = 2010,
                          geometry=TRUE) %>% 
                    filter(NAME=="Colorado")

```

```{r}
# plot Colorado polygon
tm_shape(CO_polygon)+
  tm_polygons()
```

```{r}
# extract CO elevation raster
co_elevation<-get_elev_raster(locations=CO_polygon, proj=CO_polygon, z=9, clip="locations")
```

```{r}
# print raster metadata
co_elevation
```

```{r}
# create colorado elevation map and assign to "CO_elevation_map" object
CO_elevation_map<-tm_shape(co_elevation)+
                      tm_raster(title="Elevation in Colorado (m)")+
                      tm_legend(outside=T)
```

```{r}
# print "CO_elevation_map"
CO_elevation_map
```

Click [here](https://rspatialdata.github.io/elevation.html) for a more detailed tutorial published by *rspatialdata*. 



